# Generated by Django 4.2 on 2023-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='site',
            new_name='site_nombre',
        ),
    ]
