# Generated by Django 4.2 on 2023-04-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0003_alter_paciente_dni_alter_paciente_numero_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_protocolo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='site_numero',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_paciente',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
