# Generated by Django 4.1.7 on 2023-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0005_alter_paciente_dni_alter_paciente_numero_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='investigador',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
