# Generated by Django 4.1.7 on 2023-04-13 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0006_paciente_investigador'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='invest_NOenmasc',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolo',
            name='invest_enmasc',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolo',
            name='invest_princ',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolo',
            name='site',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
