# Generated by Django 4.1.7 on 2023-04-17 23:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0008_protocolo_site_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_visita',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='visita',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
