# Generated by Django 4.2 on 2023-04-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0009_paciente_fecha_visita_paciente_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comentario',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
