# Generated by Django 4.2 on 2023-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TApp', '0010_paciente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_paciente',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
